name: Build Onix Worker

# Build and push serverless worker img upon change to the main branch's worker dir

on:
 push:
   branches: [main]
   paths:
     - "worker/**"
     - ".github/workflows/build.yml"
 workflow_dispatch: {}
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write

   steps:
     - name: Check repo
       uses: actions/checkout@v4

     - name: Log in to Github Container Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      
     - name: Build and push img
       uses: docker/build-push-action@v6
       with:
         context: ./worker
         push: true
         tags: ghcr.io/${{ github.repository_owner }}/onixworker:v1.2  
